<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MSI" failures="1" tests="4" name="Error Validation Test" time="81.303" errors="0" timestamp="2024-02-13T23:27:01 IST">
  <testcase classname="Amazon.Frameworkdesign.tests.ErrorValidationsTest" name="LoginErrorValidation" time="1.475">
    <skipped/>
  </testcase> <!-- LoginErrorValidation -->
  <testcase classname="Amazon.Frameworkdesign.tests.ErrorValidationsTest" name="LoginErrorValidation" time="0.614">
    <failure type="java.lang.AssertionError" message="expected [Login Successfully] but found [Login Successfully1]">
      <![CDATA[java.lang.AssertionError: expected [Login Successfully] but found [Login Successfully1]
at Amazon.Frameworkdesign.tests.ErrorValidationsTest.LoginErrorValidation(ErrorValidationsTest.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- LoginErrorValidation -->
  <testcase classname="Amazon.Frameworkdesign.tests.ErrorValidationsTest" name="ProductErrorValidation" time="14.244"/>
  <testcase classname="Amazon.Frameworkdesign.tests.ErrorValidationsTest" name="ProductErrorValidation" time="2.255"/>
</testsuite> <!-- Error Validation Test -->
